CREATE TABLE IF NOT EXISTS challenges (
    id SERIAL PRIMARY KEY,
    uid BIGINT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    is_done BOOLEAN DEFAULT FALSE,
    od_obj SMALLINT NULL,
    od_ach SMALLINT NULL,
    tb_obj SMALLINT NULL,
    tb_ach SMALLINT NULL,
    start_at TIMESTAMPTZ NOT NULL,
    due_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT "fkey_uid" FOREIGN KEY (uid) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE
);
